// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK1f-09Kyr22BIj_z62pTQPvSeYxWdLCU',
    appId: '1:1016120424987:web:dfd2238a742e58f0aa16be',
    messagingSenderId: '1016120424987',
    projectId: 'chatapp-532b8',
    authDomain: 'chatapp-532b8.firebaseapp.com',
    storageBucket: 'chatapp-532b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5SLkyh1qkI5jENHvpLXw2WP_ws9-SRms',
    appId: '1:1016120424987:android:c3c26834c17aacdaaa16be',
    messagingSenderId: '1016120424987',
    projectId: 'chatapp-532b8',
    storageBucket: 'chatapp-532b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw63r_uAbInchaGPeli4C8PoGQQahfpm4',
    appId: '1:1016120424987:ios:aa495c3fb20dcc52aa16be',
    messagingSenderId: '1016120424987',
    projectId: 'chatapp-532b8',
    storageBucket: 'chatapp-532b8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw63r_uAbInchaGPeli4C8PoGQQahfpm4',
    appId: '1:1016120424987:ios:aa495c3fb20dcc52aa16be',
    messagingSenderId: '1016120424987',
    projectId: 'chatapp-532b8',
    storageBucket: 'chatapp-532b8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK1f-09Kyr22BIj_z62pTQPvSeYxWdLCU',
    appId: '1:1016120424987:web:b58d450b4da9e8c5aa16be',
    messagingSenderId: '1016120424987',
    projectId: 'chatapp-532b8',
    authDomain: 'chatapp-532b8.firebaseapp.com',
    storageBucket: 'chatapp-532b8.appspot.com',
  );
}
